Wip multiprocess
nullndr/ScraperParlamentari pull request #3
Opened 2022-09-09 12:41 UTC by Anulo2

Ho provato a fare qualcosa per il multiprocessing per parallelizzare pure le 2 scansioni. Necessita ancora un po' di debug per vedere se è sufficientemente stabile

2022-09-09 12:57 UTC, nullndr commented on main.py
> +
Questa riga possiamo eliminarla

2022-09-09 12:58 UTC, nullndr commented on main.py
> +    #print(f'\nI senatori sono {bold(globals()[color](senators_number))}, di cui {bold(globals()[color](senators_without_email))} dotati di indirizzo e-mail e {bold(globals()[color](senators_with_ema
Stesso commento sopra

2022-09-09 13:01 UTC, nullndr commented on main.py
> +        print(f'\nI {value} sono {bold(globals()[return_dict[value][4]](return_dict[value][1]))}, di cui {bold(globals()[return_dict[value][4]](return_dict[value][2]))} dotati di indirizzo e-mail e {
Questa riga è parecchio lunga, riesci ad estrarre le parte della stringa?

2022-09-09 13:03 UTC, nullndr requested changes
In generale ok, per i commenti puoi farla in questa o possiamo eliminarli più avanti.

Sarebbe bene inoltre se tipizzassimo le variabili.

2022-09-14 12:44 UTC, Anulo2 commented
Ho sistemato tutti i commenti che avevi fatto. Non ho ancora tipizzato. Se vuoi intanto uniscila pure tanto per non lasciare la pr aperta in eterno.

2022-09-14 12:51 UTC, nullndr commented on main.py
> +from utils import blue, bold, cyan, red
`cyan` e `red` non sono più usati

2022-09-14 12:52 UTC, nullndr commented on main.py
> +def process_deputies_by_letter(color, char):
`color` non è utilizzato

2022-09-14 12:52 UTC, nullndr commented on main.py
> +        #print(f' - {globals()[color](id)}\n\t- {bold(lastname)}\n\t- {bold(firstname)}\n\t- {bold(email)}\n')
Queste righe sono inutili

2022-09-14 12:52 UTC, nullndr commented on main.py
> +def process_senators_by_letter(color, char):
`color` non è utilizzato

2022-09-14 12:53 UTC, nullndr commented on main.py
> +        #print(f' - {globals()[color](id)}\n\t- {bold(lastname)}\n\t- {bold(firstname)}\n\t- {bold(email)}\n')
Queste righe sono inutili

2022-09-14 12:53 UTC, nullndr requested changes
Ci sono alcuni parametri inutilizzati

2022-09-16 07:56 UTC, nullndr approved these changes

2022-09-16 07:56 UTC, merged